import type { ProviderModelConfig } from "@oh-my-pi/pi-coding-agent";

/**
 * List of all 16 models available in Zed (Claude, GPT, Gemini series).
 */
export const ZED_MODELS: ProviderModelConfig[] = [
  // --- Anthropic Claude Series ---
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5 (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 16384,
    cost: {
      input: 3.3,
      output: 16.5,
      cacheRead: 0.33,
      cacheWrite: 4.125,
    },
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6 (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 8192,
    cost: {
      input: 3.3,
      output: 16.5,
      cacheRead: 0.33,
      cacheWrite: 4.125,
    },
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5 (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 8192,
    cost: {
      input: 3.3,
      output: 16.5,
      cacheRead: 0.33,
      cacheWrite: 4.125,
    },
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5 (Zed)",
    api: "openai-completions",
    reasoning: false,
    input: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 8192,
    cost: {
      input: 1.1,
      output: 5.5,
      cacheRead: 0.11,
      cacheWrite: 1.375,
    },
  },

  // --- OpenAI GPT Series ---
  {
    id: "gpt-5.6-sol",
    name: "GPT-5.6 Sol (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 400000,
    maxTokens: 16384,
    cost: {
      input: 5.5,
      output: 33.0,
      cacheRead: 0.55,
      cacheWrite: 0,
    },
  },
  {
    id: "gpt-5.6-terra",
    name: "GPT-5.6 Terra (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 400000,
    maxTokens: 16384,
    cost: {
      input: 5.5,
      output: 33.0,
      cacheRead: 0.55,
      cacheWrite: 0,
    },
  },
  {
    id: "gpt-5.6-luna",
    name: "GPT-5.6 Luna (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 400000,
    maxTokens: 16384,
    cost: {
      input: 5.5,
      output: 33.0,
      cacheRead: 0.55,
      cacheWrite: 0,
    },
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5 (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 400000,
    maxTokens: 16384,
    cost: {
      input: 5.5,
      output: 33.0,
      cacheRead: 0.55,
      cacheWrite: 0,
    },
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4 (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 400000,
    maxTokens: 16384,
    cost: {
      input: 2.75,
      output: 16.5,
      cacheRead: 0.0275,
      cacheWrite: 0,
    },
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3 Codex (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 400000,
    maxTokens: 16384,
    cost: {
      input: 1.925,
      output: 15.4,
      cacheRead: 0.1925,
      cacheWrite: 0,
    },
  },
  {
    id: "gpt-5.2",
    name: "GPT-5.2 (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 400000,
    maxTokens: 16384,
    cost: {
      input: 1.925,
      output: 15.4,
      cacheRead: 0.1925,
      cacheWrite: 0,
    },
  },
  {
    id: "gpt-5-mini",
    name: "GPT-5 Mini (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 400000,
    maxTokens: 16384,
    cost: {
      input: 0.275,
      output: 2.2,
      cacheRead: 0.0275,
      cacheWrite: 0,
    },
  },
  {
    id: "gpt-5-nano",
    name: "GPT-5 Nano (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 400000,
    maxTokens: 16384,
    cost: {
      input: 0.055,
      output: 0.44,
      cacheRead: 0.0055,
      cacheWrite: 0,
    },
  },

  // --- Google Gemini Series ---
  {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 8192,
    cost: {
      input: 2.2,
      output: 13.2,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 8192,
    cost: {
      input: 1.65,
      output: 9.9,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
  {
    id: "gemini-3-flash",
    name: "Gemini 3 Flash (Zed)",
    api: "openai-completions",
    reasoning: true,
    input: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 8192,
    cost: {
      input: 0.55,
      output: 3.3,
      cacheRead: 0,
      cacheWrite: 0,
    },
  },
];
